### ISSUE TITLE
Prueba issues

### ISSUE THREAD

**Issue by beperev** [PRBD2021/PruebasForoPublic#1]
No me sale el ejercicio 2

**Comment by beatrizunex** [comment]
Soy Beatrizunex, tengo acceso triagle y estoy escribiendo un comentario

**Comment by beatrizunex** [comment]
Soy beatrizunex y no me da opción de cerrar el issue

**Comment by beatrizunex** [comment]
Tampoco puedo añadir usuarios como assignees ni modificar ningún aspecto

**Comment by beperev** [comment]
como beperev sí puedo cerrar el comentario.
